spring.application.name=user-service
# Use fixed port locally, random only in cloud
server.port=8080
# server.port=${PORT:0}

eureka.instance.instance-id=${spring.application.name}:${random.value}

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/microservices_users
spring.datasource.username=postgres
spring.datasource.password=Postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logging Hibernate SQL
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace

# Disable Ribbon (deprecated in Spring Cloud)
spring.cloud.loadbalancer.ribbon.enabled=false
