server:
  port: 8090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/students/**
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/courses/**
        - id: exam-service
          uri: lb://EXAM-SERVICE
          predicates:
            - Path=/api/exams/**
        - id: answer-service
          uri: lb://ANSWER-SERVICE
          predicates:
            - Path=/api/answers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
