spring.application.name=answer-service
server.port=8083

# Eureka Discovery
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# MongoDB Configuration
spring.data.mongodb.uri=mongodb://mongodb:mongodb@localhost:27017/microservices_answers_db?authSource=admin

# Exclude JDBC since we’re not using RDBMS here
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Disable Ribbon (deprecated)
spring.cloud.loadbalancer.ribbon.enabled=false
spring.cloud.compatibility-verifier.enabled=false

