spring.application.name=api-gateway-service
server.port=8090

# Eureka Discovery Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable Gateway Discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# USER SERVICE
spring.cloud.gateway.routes[0].id=user-core
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/students/**

# COURSE SERVICE
spring.cloud.gateway.routes[1].id=course-core
spring.cloud.gateway.routes[1].uri=lb://course-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/courses/**

# EXAM SERVICE
spring.cloud.gateway.routes[2].id=exam-core
spring.cloud.gateway.routes[2].uri=lb://exam-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/exams/**

# ANSWER SERVICE
spring.cloud.gateway.routes[3].id=answer-core
spring.cloud.gateway.routes[3].uri=lb://answer-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/answers/**

# Disable Ribbon (deprecated in new Spring Cloud versions)
spring.cloud.loadbalancer.ribbon.enabled=false
